version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: antera-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:lawrance24@db:5432/antera2?schema=public
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    command: npm start

  db:
    image: postgres:16-alpine
    container_name: antera-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lawrance24
      POSTGRES_DB: antera2
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
